[build]
  base = "frontend"
  command = "npm run build && npm run test:e2e"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://mechanical-repair-app.onrender.com"

[[plugins]]
  package = "netlify/plugin-playwright"

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/qa"
  to = "/playwright-report/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://mechanical-repair-app.onrender.com/:splat"
  status = 200
  force = true