[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "https://mechanical-repair-backend.onrender.com/api/:splat"
  status = 200
  force = true