[build]
  base = "frontend"
  command = "npm run build && npm run test:e2e:report"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-playwright"

# Route for Playwright report
[[redirects]]
  from = "/qa"
  to = "/playwright-report/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "${VITE_API_BASE}/:splat"
  status = 200
  force = true

